BLUEBUTTON-1192: Verify database queries
CMSgov/bluebutton-ansible-playbooks-data pull request #56
Opened 2019-08-16 14:59 UTC by jcgeer

First draft of bash script to verify database queries

2019-08-16 15:14 UTC, karlmdavis requested changes
Great start! Some suggestions/fixes, but they're all rather minor.

2019-08-16 15:14 UTC, karlmdavis commented on dev/verify-db-queries.sh
> +username = "postgres"
Please make `dbname`, `username` and other variables that are either security sensitive or variable, either arguments or environment variables, rather than a constant.

2019-08-16 15:14 UTC, karlmdavis commented on dev/verify-db-queries.sh
> +	`psql -U $username -d $dbname -c "select beneficiar0_.\"beneficiaryId\" as benefici1_0_0_, beneficiar1_.\"beneficiaryHistoryId\" as benefici1_1_1_, medicarebe2_.\"medicareBeneficiaryIdKey\" as medic
Will this time out after 30 seconds? Or are you just expecting that Jo's script will kill it (which might take up to 120 seconds, FYI).

I'd probably use `statement_timeout`, per https://dba.stackexchange.com/a/164450.

2019-08-16 15:14 UTC, karlmdavis commented on dev/verify-db-queries.sh
> +	`psql -U $username -d $dbname -c "select beneficiar0_.\"beneficiaryId\" as benefici1_0_, beneficiar0_.\"ageOfBeneficiary\" as ageOfBen2_0_, beneficiar0_.\"beneEnrollmentReferenceYear\" as beneEnro3_
I'd probably write a Bash function for all of your calls to `psql`, so you can reuse logic, per https://www.tldp.org/LDP/abs/html/functions.html.

2019-08-16 15:14 UTC, karlmdavis commented on dev/verify-db-queries.sh
> +	fi
You'll need to do this for every query, which is another good reason to build a reuseable function (see below).

2019-08-16 15:14 UTC, karlmdavis commented on dev/verify-db-queries.sh
> +`psql -U $username -d $dbname -c "SET statement_timeout TO 15000"`
FYI: You don't actually need the backticks unless you're assigning the output to a variable.

2019-08-16 15:26 UTC, jcgeer commented on dev/verify-db-queries.sh
> +	`psql -U $username -d $dbname -c "select beneficiar0_.\"beneficiaryId\" as benefici1_0_0_, beneficiar1_.\"beneficiaryHistoryId\" as benefici1_1_1_, medicarebe2_.\"medicareBeneficiaryIdKey\" as medic
I've set it to 15 seconds that way earlier in the script, line 13. Do we want it at 30 seconds?

2019-08-16 15:44 UTC, karlmdavis commented on dev/verify-db-queries.sh
> +	`psql -U $username -d $dbname -c "select beneficiar0_.\"beneficiaryId\" as benefici1_0_0_, beneficiar1_.\"beneficiaryHistoryId\" as benefici1_1_1_, medicarebe2_.\"medicareBeneficiaryIdKey\" as medic
I missed that, but did you test it yet?

I'm pretty sure that `SET` statements like that are per-session, and each `psql` command you're running will be in a separate session.

2019-08-16 16:25 UTC, jcgeer commented on dev/verify-db-queries.sh
> +	`psql -U $username -d $dbname -c "select beneficiar0_.\"beneficiaryId\" as benefici1_0_0_, beneficiar1_.\"beneficiaryHistoryId\" as benefici1_1_1_, medicarebe2_.\"medicareBeneficiaryIdKey\" as medic
From reading further it looks like you're right, it is per-session. I didn't realize each `psql` command would be in a separate session. I've added it into a new function to perform before each statement is run.

2019-08-16 20:27 UTC, karlmdavis requested changes
Still needs one change.

2019-08-16 20:27 UTC, karlmdavis commented on dev/verify-db-queries.sh
> +randomBeneIds=( $(psql -U $USERNAME -d $DBNAME -c "SELECT beneficiaryId FROM Beneficiaries ORDER BY RANDOM() LIMIT $NUMBENESTOQUERY") )
Why the extra parentheses here? Won't hurt anything, I don't think, but it causes the command to be run in a subshell.

https://www.tldp.org/LDP/abs/html/subshells.html

2019-08-16 20:27 UTC, karlmdavis commented on dev/verify-db-queries.sh
> +	psql -U $USERNAME -d $DBNAME $dbQuery
This still won't work with the timeout: you're still running it in a separate process, which means it's a separate session. Try this, instead (per the `psql` man page: http://manpages.ubuntu.com/manpages/bionic/man1/psql.1.html):

```suggestion
	psql -U $USERNAME -d $DBNAME <<EOF
SET statement_timeout TO 15000;
${dbQuery}
EOF
```

This odd `<<EOF` construct is called a "heredoc" in Bash, and they're weird, but useful: http://tldp.org/LDP/abs/html/here-docs.html.

2019-08-16 20:31 UTC, jcgeer commented on dev/verify-db-queries.sh
> +randomBeneIds=( $(psql -U $USERNAME -d $DBNAME -c "SELECT beneficiaryId FROM Beneficiaries ORDER BY RANDOM() LIMIT $NUMBENESTOQUERY") )
Must have added those accidentally.

2019-08-16 20:37 UTC, jcgeer commented on dev/verify-db-queries.sh
> +	psql -U $USERNAME -d $DBNAME $dbQuery
Thanks for the documentation on this. I wasn't sure how to do it otherwise, obviously.

2019-08-16 20:47 UTC, karlmdavis requested changes
One last thing.

2019-08-16 20:47 UTC, karlmdavis commented on dev/verify-db-queries.sh
> +	EOF
I think you need to remove the leading whitespace on the last three lines of this block, as the heredoc won't trim it -- it'll run those commands with the spaces, as written. I know it looks weird like that, but that's how they work.

(The spaces are probably fine in this context: I don't think SQL queries care, but it's best to not get in the habit.)

2019-08-16 20:49 UTC, jcgeer commented on dev/verify-db-queries.sh
> +	EOF
Fair enough. I see I hadn't read that far down into the documentation yet.

2019-08-16 21:17 UTC, karlmdavis approved these changes
Approved, though as mentioned: please verify on TEST that this works as expected with a load test before deploying to DPR and PROD.

Great work!

2019-08-19 02:54 UTC, karlmdavis commented
Went to run this myself out in TEST this weekend and realized it needed some work. Hope you don't mind, but just pushed my changes here.

It's now working.

Notes:

* Still not 100% done: I left a lot of queries out.
* May want to rework it further to run some or all of the queries within the same DB connection, as we're wasting a lot of time connecting, disconnecting, etc.
    * This is the same reason that we use a DB connection pool in our app code.
    * On the other hand, if we're just going to run everything in the same connection, we should consider using `pgbench`, instead.
* I ran this in TEST today for 100K benes, with only the carrier claims query enabled. It didn't find any timeouts.
    * Maybe TEST just doesn't have enough data?
    * Maybe there's something else about PROD that causes these problems to appear?
    * Maybe the problem only shows up when lots of other queries are also being run?
    * ... not sure. Now have a run going in TEST with all the query-by-bene-ID queries enabled.

2019-08-30 19:35 UTC, karlmdavis commented
Closing this PR, as the project has now been migrated into a new monorepo: https://github.com/CMSgov/beneficiary-fhir-data

2019-08-30 19:35 UTC, closed without merging